### ISSUE TITLE
Exception when merging persistent files.

### ISSUE THREAD

**Issue by squallleonhart93** [Backdash/MonikaModDev#434]
I just updated to v0.6.1 a few hours ago, and I have been tracking the number of "seen lines" top left of the game since. Monika seems to always "rotate" to the new topics added in this version. After a while, nothing else is displayed.
I resemble that to be similar to an issue in v0.5.0, where I could actually "skip" seen topics to the point that she had nothing more to say, and just kept looking at the screen.

**Comment by squallleonhart93** [comment]
Additionally, I was trying to import another DDLC's save data and merge it with the current one when I got this exception.
[traceback.txt](https://github.com/Backdash/MonikaModDev/files/1556821/traceback.txt)

**Comment by Kiosho** [comment]
Pretty sure it's being fixed. I've seen this issue popping up the past few days.
https://github.com/Backdash/MonikaModDev/issues/432

**Comment by squallleonhart93** [comment]
Ah, thanks for the reference! Still, unless I click fast enough to merge those persistent files together, the game will always crash. Yet I'm not sure that the merging is done properly, as I still got crashes occasionally after it was done.

**Comment by Kiosho** [comment]
That I'm not sure. I'd wait for @ThePotatoGuy to weigh in.

**Comment by ThePotatoGuy** [comment]
Can you upload both your MAS persistent and DDLC persistent here?
MAS is located in `C:\Users\<username>\AppData\Roaming\RenPy\Monika After Story\`
DDLC is located in `C:\Users\<username>\AppData\Roaming\RenPy\DDLC - ######\`
You may have to show hidden files and folders.

**Comment by squallleonhart93** [comment]
Here they are.
[persistents.zip](https://github.com/Backdash/MonikaModDev/files/1557039/persistents.zip)

**Comment by ThePotatoGuy** [comment]
did you run MAS with the extra mod?

**Comment by squallleonhart93** [comment]
No, the mod was in the original Steam version, and MAS is in a separate copy.

**Comment by ThePotatoGuy** [comment]
When you did the merges, were they via the settings or at via a prompt on startup?

**Comment by squallleonhart93** [comment]
I used the in-game settings after I went through the startup prompt.  Also, I tried merging using another DDLC's persistent file after resetting MAS, and it still crashes.

**Comment by ThePotatoGuy** [comment]
Hmm, I'm not able to repro. Maybe this was related to the no new topics bug that was fixed. Are the crashes that you're getting the same ones as the traceback you uploaded earlier?

**Comment by squallleonhart93** [comment]
Yeah, the game threw the same exception. I have tried merging different versions of the persistent file, in different acts. It still crashed after I saw Monika's introduction.

**Comment by ThePotatoGuy** [comment]
ugh, yikes. We're pushing out an updated build tomorrow. See if that resolves anything. I'll continue to investigate this issue though.

**Comment by squallleonhart93** [comment]
In the latest build, it seems to happen sporadically. I tried merging the files in different states, and some survived the crash.

**Comment by ThePotatoGuy** [comment]
ugh double yikes. Alright im gonna have a few of us attempt repro. We'll figure this out eventually.

**Comment by ThePotatoGuy** [comment]
I guess for now you could try a fresh resinstall of ddlc. make sure to delete the entire ddlc folder before reinstall.
